import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { FloatingDockDemo } from "./FloatingDock";
import ChatBot from "@/components/chatbot";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body className={inter.className}>
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7916766114053705"
     crossorigin="anonymous"></script>
<!-- When naming your Google AdSense ad units, it's important to choose names that not only reflect the placement and purpose of the ads but also help you keep track of performance effectively. Consider using descriptive yet professional names like PrimeSpot AdBlock or TopView AdSlot, which hint at high visibility and prime positioning. You could also opt for names that convey engagement and user interaction, such as EngageAds or SmartAd Placement. If your content is niche-specific, like tech or lifestyle, you could tailor names like TechTrend Ads or ContentFlow Ads to reflect your site's theme. This way, your ad units remain organized and aligned with your content, enhancing both user experience and ad performance. -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-7916766114053705"
     data-ad-slot="8892839815"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          <div className="min-h-screen flex flex-col  ">
            <Navbar />
            <div className="flex">
              <Sidebar />
              <main className="flex-1 p-4">
                {children}
                <ChatBot />
              </main>
            </div>
            <footer>
              <div className="dock fixed bottom-5 left-1/2 transform -translate-x-1/2 ">
                {/* <FloatingDockDemo /> */}
              </div>

            </footer>
            {/* <iframe src="https://bot.elephant.ai/46b68a4d-5021-4644-80c7-74678d6c5d06" width="100%" style={{ height: "100%", minHeight: "700px" }} frameBorder="0"></iframe> */}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
